CREATE TABLE dataset (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount_usd NUMERIC(10,2),
    location VARCHAR(100),
    size VARCHAR(10),
    color VARCHAR(50),
    season VARCHAR(30),
    review_rating NUMERIC(3,1),
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases NUMERIC(10,2),
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50)
);

ALTER TABLE dataset
ALTER COLUMN size TYPE VARCHAR(50);

SELECT COUNT(*) FROM dataset;

SELECT * FROM dataset;

/* Business Questions
*/

-- 1. Which category generates highest revenue?
SELECT
	category,
	sum(purchase_amount_usd) as revenue
FROM dataset
GROUP BY category
ORDER BY revenue DESC;

/* Impacts
- Helps prioritize high-performacing categories
- Optimizes inventory planning
- Improves marketing ROI
*/

-- 2. Are discounts actually increasing purchase value?
SELECT
	discount_applied,
	sum(purchase_amount_usd),
	round(AVG(purchase_amount_usd),2)
FROM dataset
GROUP BY discount_applied;

/* Business problem: Discounts may reduce profit without increasing sales
Impact:
- Identify effectiveness of discounts
- Reduce unnecessary discounts costs
- Improve profit margins
*/

-- 3. What is total revenue generated by male and female customers?
SELECT
	gender,
	sum(purchase_amount_usd) as total_revenue,
	count(customer_id) as total_transactions
FROM dataset
GROUP BY gender
ORDER BY total_revenue DESC;

/* Business problem: Lack of understanding of revenue contribution by gender segments.
Impact:
- Helps design targeted marketing campigns
- Improves customer segmentation strategy
- Enhances personalization efforts
*/

-- 4. Which customer used a discount but still spent more than the average purchase amount?
SELECT
	customer_id,
	purchase_amount_usd,
	discount_applied
FROM dataset
WHERE discount_applied = 'Yes' and purchase_amount_usd > (SELECT AVG(purchase_amount_usd) FROM dataset);

/* Business problem: Company cannot identify high-spending customers who are also discount users.
Impact:
- Identifies premium discount-sensitive customers
- Enables targeted discount campigns
- Improves customer retention and revenue
*/

-- 5. Which are top / bottm 5 products with the highest average review rating.

SELECT
	item_purchased,
	AVG(review_rating) AS avg_rating
FROM dataset
GROUP BY item_purchased
ORDER BY avg_rating DESC;

SELECT
	item_purchased,
	AVG(review_rating) AS avg_rating
FROM dataset
GROUP BY item_purchased
ORDER BY avg_rating ASC;

/* Business problem: No visibility into product performance based on customer satisfaction
Impact:
- Promotes high performacing products
- Improves low rated products
- Enhances customer experience
*/

-- 6. Average purchase: Standard vs Express shipping

SELECT 
	shipping_type,
	COUNT(DISTINCT customer_id) as order_placed,
	sum(purchase_amount_usd) as revenue
FROM dataset
GROUP BY shipping_type
ORDER BY revenue DESC;

/* Business problem: Unclear if faster shipping leads to highest spending.
Impact:
- Helps optimizies shipping price strategy.
- Encourages premium shippind adoption.
- Increse average order value
*/

-- 7. Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non-subscribers.

SELECT
	subscription_status,
	COUNT(customer_id) as users,
	ROUND(AVG(purchase_amount_usd),2) as avg_revenue,
	ROUND(SUM(purchase_amount_usd),2) as total_revenue
FROM dataset
GROUP BY subscription_status
ORDER BY total_revenue DESC;

/* Business problem: The effectiveness of subscription program is unknown.
Impact:
- Validates subscription model performance.
- Improves customer loyalty programs.
- Increases customer lifetime value (CLV).
*/

-- 8. Top 5 products with highest discount usage %

SELECT 
	item_purchased,
	COUNT(item_purchased) AS total_number_of_times_sold,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS Number_of_times_sold_when_discount_applied,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) as discount_percent
FROM dataset
GROUP BY item_purchased
ORDER BY discount_percent DESC;

/* Business problem: Some products may be overly dependent on discounts
Impact:
- Identifies discount driven products
- Helps optimize pricing strategy
- Reduces profit margin loss
*/
 
-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment.

select
	case
		when previous_purchases = '0' then 'New customer'
		when previous_purchases between 1 and 15 then 'Returning customer'
	else 'Loyal customer'
end as customer_segment,
count(*) as customer_count
from dataset
group by customer_segment;

/* Business problem: Lack of customer segmentation leads to generic strategies
Impact:
- Enables personalized marketing
- Improves retention strategies
- Increases conversion rates
*/

-- 10. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS total,
    ROUND(
        COUNT(*) * 100.0 
        / SUM(COUNT(*)) OVER (PARTITION BY 
            CASE 
                WHEN previous_purchases > 5 THEN 'Repeat Buyer'
                ELSE 'Normal Buyer'
            END
        ), 2
    ) AS percentage
FROM dataset
GROUP BY customer_type, subscription_status;

/* Business problem: The compant doesn't know top performing products within categories
Impact:
- Improves product placement & recommendations
- Helps inventory optimization
- Increases sales through best seller
*/

-- 11. What are the top 3 most purchased products within each category?

with cte as(
select 
	category,
	item_purchased,
	count(item_purchased) as most_purchased,
	rank() over(partition by category order by count(item_purchased) desc) as rnk
from dataset
group by category, item_purchased
)
select * from cte
where rnk<=3;

/* Business problem: Unclear relationship between loyalty and suubscription
Impact:
- Improves sunscription targeting
- Increases conversion to paid programs
- Increases customer retention streategy
*/

-- 12. What is the revenue contribution of each age group?

select
	case
		when age between 18 and 25 then '18-25'
		when age between 26 and 35 then '26-35'
		when age between 36 and 50 then '36-50'
	else '51+'
	end as age_group,
	round(sum(purchase_amount_usd), 2) as revenue
from dataset
group by age_group
order by revenue desc;

/* Business problem: No visibility into which age group contribution most to revenue
Impact:
- Enables age base targetting
- Enhances marketing efficiency
*/
